root-version: v2.3.0
applications:
  service-a:
    image: ghcr.io/jhbaek-dev/k8s-blue-green-demo/service-a:qa-d6c406b-20250825-095053
  service-b:
    image: ghcr.io/jhbaek-dev/k8s-blue-green-demo/service-b:qa-5b2b467-20250828-063430
  service-c:
    image: ghcr.io/jhbaek-dev/k8s-blue-green-demo/service-c:qa-5b2b467-20250828-063430
