apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        root-version: v2.1.1
    spec:
      containers:
        - name: service-b
          image: SERVICE_B_IMAGE
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: service-b
      previewService: service-b-preview
