apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        root-version: v2.0.0_qa
    spec:
      containers:
        - name: service-b
          image: ghcr.io/jhbaek-dev/k8s-blue-green-demo/service-b:qa-6f1ec00-20250823-021148
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: service-b
      previewService: service-b-preview
