apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-b-vc
  namespace: default
spec:
  hosts:
    - service-b
  http:
    - match:
        - sourceLabels:
            root-version: "v2.2.0"
      route:
        - destination:
            host: service-b-preview
            port:
              number: 3000
    - route:
        - destination:
            host: service-b
            port:
              number: 3000
